<?php
namespace App\Services;
use App\Models\FuelRequest; use App\Models\User; use App\Models\Vehicle; use Illuminate\Support\Facades\DB;
class FuelRequestService
{
 public function createDraft(User $actor,array $attributes): FuelRequest { $this->ensureOperationalActor($actor); return DB::transaction(function() use($actor,$attributes){ $vehicle=Vehicle::query()->lockForUpdate()->findOrFail($attributes['vehicle_id']); $odometer=(int)($attributes['odometer']??0); $this->ensureActiveVehicleAndValidOdometer($vehicle,$odometer,$attributes['fuel_type_id']); return FuelRequest::create(['request_number'=>$this->nextRequestNumber(),'requested_at'=>$attributes['requested_at']??now(),'vehicle_id'=>$vehicle->id,'requester_person_id'=>$attributes['requester_person_id']??null,'responsible_sector'=>$attributes['responsible_sector']??null,'driver_person_id'=>$attributes['driver_person_id']??null,'fuel_type_id'=>$attributes['fuel_type_id'],'odometer'=>$odometer,'requested_liters'=>$attributes['requested_liters']??null,'estimated_amount'=>$attributes['estimated_amount']??null,'notes'=>$attributes['notes']??null,'status'=>'draft','created_by_user_id'=>$actor->id]); }); }
 public function submit(User $actor,int $requestId): FuelRequest { $this->ensureOperationalActor($actor); return DB::transaction(function() use($actor,$requestId){ $request=FuelRequest::query()->lockForUpdate()->findOrFail($requestId); $vehicle=Vehicle::query()->lockForUpdate()->findOrFail($request->vehicle_id); if($request->status!=='draft') throw new OperationalStateException('Somente requisições em rascunho podem ser enviadas.'); if(!$actor->isSupervisor() && $request->created_by_user_id!==$actor->id) throw new OperationalPermissionException('Apenas o criador pode enviar esta requisição.'); $this->ensureActiveVehicleAndValidOdometer($vehicle,(int)$request->odometer,$request->fuel_type_id); $request->update(['status'=>'submitted']); return $request->fresh(); }); }
 public function approve(User $actor,int $requestId): FuelRequest { $this->ensureSupervisor($actor); return DB::transaction(function() use($actor,$requestId){ $request=FuelRequest::query()->lockForUpdate()->findOrFail($requestId); if(!$request->canBeApproved()) throw new OperationalStateException('Somente requisições enviadas podem ser aprovadas.'); $approvedAt=now(); $changes=['status'=>'approved','approved_by_user_id'=>$actor->id,'approved_at'=>$approvedAt,'rejection_reason'=>null]; if($request->requiresAuthorization()){$changes['authorization_at']=$approvedAt;$changes['authorization_expires_at']=$approvedAt->copy()->addDays(3);} $request->update($changes); return $request->fresh(); }); }
 public function reject(User $actor,int $requestId,string $reason): FuelRequest { $this->ensureSupervisor($actor); $reason=trim($reason); if($reason==='') throw new OperationalStateException('O motivo da rejeição é obrigatório.'); return DB::transaction(function() use($actor,$requestId,$reason){ $request=FuelRequest::query()->lockForUpdate()->findOrFail($requestId); if(!$request->canBeApproved()) throw new OperationalStateException('Somente requisições enviadas podem ser rejeitadas.'); $request->update(['status'=>'rejected','approved_by_user_id'=>$actor->id,'approved_at'=>now(),'rejection_reason'=>$reason]); return $request->fresh(); }); }
 public function cancel(User $actor,int $requestId): FuelRequest { return DB::transaction(function() use($actor,$requestId){ $request=FuelRequest::query()->lockForUpdate()->findOrFail($requestId); if(!in_array($request->status,['draft','submitted'],true)) throw new OperationalStateException('Somente requisições em rascunho ou enviadas podem ser canceladas.'); if(!$actor->isSupervisor() && !($request->status==='draft' && $request->created_by_user_id===$actor->id)) throw new OperationalPermissionException('Apenas supervisor pode cancelar requisição enviada.'); if($request->fueling()->exists()) throw new OperationalStateException('Não é possível cancelar requisição com abastecimento vinculado.'); $request->update(['status'=>'canceled']); return $request->fresh(); }); }
 private function nextRequestNumber(): int { $sequence=DB::table('document_sequences')->where('name','fuel_request')->lockForUpdate()->first(); if($sequence===null) throw new OperationalStateException('Sequência de requisição não configurada.'); $next=((int)$sequence->last_value)+1; DB::table('document_sequences')->where('name','fuel_request')->update(['last_value'=>$next,'updated_at'=>now()]); return $next; }
 private function ensureOperationalActor(User $actor): void { if(!$actor->is_active || !in_array($actor->role,['user','supervisor'],true)) throw new OperationalPermissionException('Ação operacional permitida somente a usuário ou supervisor ativo.'); }
 private function ensureSupervisor(User $actor): void { if(!$actor->is_active || !$actor->isSupervisor()) throw new OperationalPermissionException('Ação permitida somente a supervisor operacional ativo.'); }
 private function ensureActiveVehicleAndValidOdometer(Vehicle $vehicle,int $odometer,int $fuelTypeId): void { if($vehicle->status!=='active') throw new OperationalStateException('O veículo não está ativo para operação.'); if($odometer<(int)$vehicle->current_odometer) throw new OperationalStateException('O hodômetro não pode ser inferior ao hodômetro atual do veículo.'); if($vehicle->fuel_type_id!==null && (int)$vehicle->fuel_type_id!==$fuelTypeId) throw new OperationalStateException('O combustível não corresponde ao combustível cadastrado para o veículo.'); }
}
