@extends('layouts.app',['title'=>'Responsáveis e setores · Frota Câmara'])
@section('content')
<p class="page-kicker">Responsabilidade operacional</p><h1>{{ $vehicle->plate }} · {{ $vehicle->model }}</h1><p class="lede">Defina o vereador responsável e os setores vinculados. Cada alteração encerra o vínculo anterior e preserva o histórico.</p>
<section class="surface"><form method="post" action="{{ route('vehicle-responsibilities.update',$vehicle) }}" style="display:grid;gap:18px">@csrf @method('put')
<label style="display:grid;gap:7px;max-width:620px"><strong>Vereador responsável</strong><select name="council_member_id" style="padding:11px;border:1px solid #cbd4cd;border-radius:7px"><option value="">Nenhum vínculo de vereador</option>@foreach($councilMembers as $person)<option value="{{ $person->id }}" @selected((int)old('council_member_id',$activeCouncil?->person_id)===$person->id)>{{ $person->full_name }}</option>@endforeach</select>@error('council_member_id')<small style="color:#b42318">{{ $message }}</small>@enderror</label>
<label style="display:grid;gap:7px;max-width:620px"><strong>Setores responsáveis</strong><textarea name="sectors" rows="4" placeholder="Um setor por linha ou separado por vírgula" style="padding:11px;border:1px solid #cbd4cd;border-radius:7px">{{ old('sectors',implode("\n",$sectors)) }}</textarea><small>Exemplo para veículo compartilhado: Transporte e TV Câmara.</small></label>
<div style="display:flex;gap:10px;flex-wrap:wrap"><button style="padding:11px 16px;border:0;border-radius:7px;background:#1f6a60;color:#fff;font-weight:700">Salvar vínculos</button><a href="{{ route('master-data.edit',['resource'=>'veiculos','record'=>$vehicle->id]) }}" style="padding:11px 16px;color:#17354f">Voltar ao veículo</a></div></form></section>
<section class="surface"><h2 style="margin-top:0;color:#17354f">Histórico de vínculos</h2><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Tipo</th><th>Responsável / setor</th><th>Início</th><th>Encerramento</th></tr></thead><tbody>@forelse($vehicle->responsibilities->sortByDesc('started_at') as $item)<tr><td style="padding:10px;border-bottom:1px solid #e5e8e3">{{ $item->responsibility_type==='council_member'?'Vereador':'Setor' }}</td><td style="padding:10px;border-bottom:1px solid #e5e8e3">{{ $item->person?->full_name ?? $item->sector }}</td><td style="padding:10px;border-bottom:1px solid #e5e8e3">{{ $item->started_at->format('d/m/Y H:i') }}</td><td style="padding:10px;border-bottom:1px solid #e5e8e3">{{ $item->ended_at?->format('d/m/Y H:i') ?? 'Vigente' }}</td></tr>@empty<tr><td colspan="4" style="padding:20px;text-align:center">Nenhum vínculo registrado.</td></tr>@endforelse</tbody></table></div></section>
@endsection
