<?php
namespace Tests\Feature;
use App\Models\FuelRequest; use App\Models\FuelType; use App\Models\User; use App\Models\Vehicle; use App\Services\FuelRequestService; use App\Services\FuelingService; use App\Services\OperationalStateException; use Carbon\Carbon; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class AuthorizationLifecycleTest extends TestCase { use RefreshDatabase;
 private function context(): array { $fuel=FuelType::create(['name'=>'Gasolina','abbreviation'=>'GAS','active'=>true]); $vehicle=Vehicle::create(['plate'=>'ABC1D23','model'=>'Teste','fuel_type_id'=>$fuel->id,'current_odometer'=>1000,'status'=>'active','maintenance_interval_km'=>10000,'maintenance_interval_days'=>180]); $user=User::create(['name'=>'Usuário','username'=>'auth-user'.uniqid(),'password'=>'SenhaLocal!12345','auth_source'=>'local','role'=>'user','is_active'=>true]); $supervisor=User::create(['name'=>'Supervisor','username'=>'auth-super'.uniqid(),'password'=>'SenhaLocal!12345','auth_source'=>'local','role'=>'supervisor','is_active'=>true]); return [$fuel,$vehicle,$user,$supervisor]; }
 public function test_approval_creates_authorization_with_three_day_validity(): void { Carbon::setTestNow('2026-08-21 10:00:00'); try { [$fuel,$vehicle,$user,$supervisor]=$this->context(); $service=app(FuelRequestService::class); $request=$service->createDraft($user,['vehicle_id'=>$vehicle->id,'fuel_type_id'=>$fuel->id,'odometer'=>1010]); $service->submit($user,$request->id); $approved=$service->approve($supervisor,$request->id); $this->assertSame('2026-08-21 10:00:00',$approved->authorization_at->toDateTimeString()); $this->assertSame('2026-08-24 10:00:00',$approved->authorization_expires_at->toDateTimeString()); $this->assertTrue($approved->canBeFulfilled()); } finally { Carbon::setTestNow(); } }
 public function test_expired_authorization_blocks_fulfillment(): void { [$fuel,$vehicle,$user,$supervisor]=$this->context(); $request=FuelRequest::create(['request_number'=>500,'requested_at'=>now()->subDays(5),'vehicle_id'=>$vehicle->id,'fuel_type_id'=>$fuel->id,'odometer'=>1010,'status'=>'approved','authorization_at'=>now()->subDays(5),'authorization_expires_at'=>now()->subDays(2),'created_by_user_id'=>$user->id]); $this->expectException(OperationalStateException::class); app(FuelingService::class)->fulfill($supervisor,['request_id'=>$request->id,'vehicle_id'=>$vehicle->id,'fuel_type_id'=>$fuel->id,'odometer'=>1020,'liters'=>20,'unit_price'=>5]); }
 public function test_request_before_cutoff_does_not_require_authorization(): void { [$fuel,$vehicle,$user]=$this->context(); $request=FuelRequest::create(['request_number'=>501,'requested_at'=>'2024-12-31 23:59:59','vehicle_id'=>$vehicle->id,'fuel_type_id'=>$fuel->id,'odometer'=>1010,'status'=>'approved','created_by_user_id'=>$user->id]); $this->assertFalse($request->requiresAuthorization()); $this->assertTrue($request->canBeFulfilled()); }
}
