<?php
namespace Tests\Feature;
use App\Models\FuelRequest; use App\Models\FuelType; use App\Models\Fueling; use App\Models\Person; use App\Models\User; use App\Models\Vehicle; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class ListActionsTest extends TestCase { use RefreshDatabase;
 private function actor(): User { return User::create(['name'=>'Supervisor','username'=>'list'.uniqid(),'password'=>'SenhaLocal!12345','auth_source'=>'local','role'=>'supervisor','is_active'=>true]); }
 private function records(User $actor): array { $fuel=FuelType::create(['name'=>'Gasolina','abbreviation'=>'GAS','active'=>true]); $vehicle=Vehicle::create(['plate'=>'ABC1D23','model'=>'Teste','fuel_type_id'=>$fuel->id,'current_odometer'=>1000,'status'=>'active','maintenance_interval_km'=>10000,'maintenance_interval_days'=>180]); $driver=Person::create(['full_name'=>'Motorista','role'=>'driver','active'=>true]); $request=FuelRequest::create(['request_number'=>20,'requested_at'=>now(),'vehicle_id'=>$vehicle->id,'driver_person_id'=>$driver->id,'fuel_type_id'=>$fuel->id,'odometer'=>1000,'status'=>'fulfilled','created_by_user_id'=>$actor->id]); $fueling=Fueling::create(['fueling_at'=>now(),'request_id'=>$request->id,'vehicle_id'=>$vehicle->id,'driver_person_id'=>$driver->id,'fuel_type_id'=>$fuel->id,'odometer'=>1010,'liters'=>20,'unit_price'=>5.5,'total_amount'=>110,'created_by_user_id'=>$actor->id]); return [$request,$fueling]; }
 public function test_request_list_exposes_accessible_quick_details_full_view_and_footer(): void { $actor=$this->actor(); [$request]=$this->records($actor); $this->actingAs($actor,'ldap')->get('/requisicoes')->assertOk()->assertSee('data-dialog="request-details-'.$request->id.'"',false)->assertSee('Autorização - 3 vias A4')->assertSee('Autorização - 3 vias Cupom')->assertSee('Abrir tela completa')->assertSee('Desenvolvido por Vaurlei de Almeida Junior')->assertSee('Setor de TI CMRP')->assertSee('versão 1.10'); }
 public function test_fueling_receipt_link_opens_in_new_tab_without_losing_list_context(): void { $actor=$this->actor(); [, $fueling]=$this->records($actor); $this->actingAs($actor,'ldap')->get('/abastecimentos')->assertOk()->assertSee('target="_blank"',false)->assertSee(route('fuelings.receipt',$fueling),false); }
}
