<?php
namespace Tests\Feature;
use App\Models\FuelType; use App\Models\User; use App\Models\Vehicle;
use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class MasterDataTest extends TestCase { use RefreshDatabase;
 private function actor(string $role): User { return User::create(['name'=>"$role test",'username'=>uniqid($role),'password'=>'SenhaLocal!12345','auth_source'=>'local','role'=>$role,'is_active'=>true]); }
 public function test_only_supervisor_accesses_master_data(): void { foreach(['user','admin'] as $role) $this->actingAs($this->actor($role),'ldap')->get('/cadastros')->assertForbidden(); $this->actingAs($this->actor('supervisor'),'ldap')->get('/cadastros')->assertOk(); }
 public function test_supervisor_creates_person_and_audit_event(): void { $actor=$this->actor('supervisor'); $this->actingAs($actor,'ldap')->post('/cadastros/pessoas',['full_name'=>'Maria da Silva','role'=>'driver','active'=>'1'])->assertRedirect(); $this->assertDatabaseHas('people',['full_name'=>'Maria da Silva','role'=>'driver']); $this->assertDatabaseHas('audit_events',['user_id'=>$actor->id,'event'=>'master_data.pessoas.created']); }
 public function test_fuel_price_is_calculated_and_vehicle_odometer_never_regresses(): void { $actor=$this->actor('supervisor'); $fuel=FuelType::create(['name'=>'Gasolina','abbreviation'=>'GAS','active'=>true]); $this->actingAs($actor,'ldap')->post('/cadastros/precos',['fuel_type_id'=>$fuel->id,'effective_at'=>'2026-08-20T10:00','valor_bruto'=>'6.000','desconto'=>'0.250'])->assertRedirect(); $this->assertDatabaseHas('valorcomb',['valorcomb'=>'5.750']); $vehicle=Vehicle::create(['plate'=>'ABC1D23','model'=>'Teste','current_odometer'=>5000,'status'=>'active','maintenance_interval_km'=>10000,'maintenance_interval_days'=>180]); $this->actingAs($actor,'ldap')->put("/cadastros/veiculos/{$vehicle->id}",['plate'=>'ABC1D23','model'=>'Teste','current_odometer'=>4999,'status'=>'active','maintenance_interval_km'=>10000,'maintenance_interval_days'=>180])->assertSessionHasErrors('current_odometer'); }
 public function test_supervisor_opens_and_updates_existing_fuel_type_without_server_error(): void { $actor=$this->actor('supervisor'); $fuel=FuelType::create(['name'=>'Não informado','abbreviation'=>'NAO INFORMAD','active'=>true]); $this->actingAs($actor,'ldap')->get("/cadastros/combustiveis/{$fuel->id}/editar")->assertOk()->assertSee('Editar Combustível')->assertSee('Nome')->assertSee('Sigla'); $this->actingAs($actor,'ldap')->put("/cadastros/combustiveis/{$fuel->id}",['name'=>'Não informado','abbreviation'=>'N/I','active'=>'1'])->assertRedirect('/cadastros/combustiveis'); $this->assertDatabaseHas('fuel_types',['id'=>$fuel->id,'abbreviation'=>'N/I']); }
}
