<?php
namespace Tests\Feature;
use App\Models\FuelRequest; use App\Models\FuelType; use App\Models\Person; use App\Models\User; use App\Models\Vehicle; use App\Models\VehicleResponsibility; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class OperationsHttpTest extends TestCase { use RefreshDatabase;
 private function user(string $role): User { return User::create(['name'=>$role,'username'=>uniqid($role),'password'=>'SenhaLocal!12345','auth_source'=>'local','role'=>$role,'is_active'=>true]); }
 private function context(): array { $fuel=FuelType::create(['name'=>'Gasolina','abbreviation'=>'GAS','active'=>true]);$vehicle=Vehicle::create(['plate'=>'ABC1D23','model'=>'Teste','fuel_type_id'=>$fuel->id,'current_odometer'=>1000,'status'=>'active','maintenance_interval_km'=>10000,'maintenance_interval_days'=>180]);$council=Person::create(['full_name'=>'Vereador Teste','role'=>'council_member','active'=>true]);VehicleResponsibility::create(['vehicle_id'=>$vehicle->id,'responsibility_type'=>'council_member','person_id'=>$council->id,'started_at'=>now()]);return [$fuel,$vehicle,$council]; }
 public function test_user_creates_submits_and_supervisor_fulfills_through_http(): void { [$fuel,$vehicle,$council]=$this->context();$user=$this->user('user');$supervisor=$this->user('supervisor');$this->actingAs($user,'ldap')->post('/requisicoes',['requested_at'=>now()->format('Y-m-d H:i:s'),'vehicle_id'=>$vehicle->id,'fuel_type_id'=>$fuel->id,'odometer'=>1010,'requested_liters'=>20])->assertRedirect();$request=FuelRequest::firstOrFail();$this->assertSame($council->id,$request->requester_person_id);$this->actingAs($user,'ldap')->post("/requisicoes/{$request->id}/enviar")->assertRedirect();$this->actingAs($supervisor,'ldap')->post("/requisicoes/{$request->id}/aprovar")->assertRedirect();$this->actingAs($supervisor,'ldap')->post("/abastecimentos/{$request->id}",['fueling_at'=>now()->format('Y-m-d H:i:s'),'odometer'=>1020,'liters'=>20,'unit_price'=>5.5])->assertRedirect();$this->assertDatabaseHas('fuel_requests',['id'=>$request->id,'status'=>'fulfilled']); }
 public function test_admin_cannot_create_request_or_record_maintenance(): void { [$fuel,$vehicle]=$this->context();$admin=$this->user('admin');$this->actingAs($admin,'ldap')->post('/requisicoes',['requested_at'=>now()->format('Y-m-d H:i:s'),'vehicle_id'=>$vehicle->id,'fuel_type_id'=>$fuel->id,'odometer'=>1010])->assertForbidden();$this->actingAs($admin,'ldap')->post('/manutencoes',['vehicle_id'=>$vehicle->id,'service_type'=>'Revisão','performed_at'=>now()->format('Y-m-d H:i:s'),'odometer'=>1010])->assertForbidden(); }
 public function test_supervisor_records_maintenance_through_http(): void { [$fuel,$vehicle]=$this->context();$supervisor=$this->user('supervisor');$this->actingAs($supervisor,'ldap')->post('/manutencoes',['vehicle_id'=>$vehicle->id,'service_type'=>'Revisão','performed_at'=>now()->format('Y-m-d H:i:s'),'odometer'=>1010,'cost'=>250,'next_maintenance_odometer'=>6000])->assertRedirect();$this->assertDatabaseHas('maintenance_records',['vehicle_id'=>$vehicle->id]); }
}
