<?php
namespace Tests\Feature;
use App\Models\FuelRequest; use App\Models\FuelType; use App\Models\Fueling; use App\Models\Person; use App\Models\User; use App\Models\Vehicle; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class ReportsAndReceiptTest extends TestCase { use RefreshDatabase;
 private function actor(): User { return User::create(['name'=>'Supervisor','username'=>'super'.uniqid(),'password'=>'SenhaLocal!12345','auth_source'=>'local','role'=>'supervisor','is_active'=>true]); }
 private function context(User $actor): array { $fuel=FuelType::create(['name'=>'Gasolina','abbreviation'=>'GAS','active'=>true]); $vehicle=Vehicle::create(['plate'=>'ABC1D23','model'=>'Teste','fuel_type_id'=>$fuel->id,'current_odometer'=>1000,'status'=>'active','maintenance_interval_km'=>10000,'maintenance_interval_days'=>180]); $driver=Person::create(['full_name'=>'Motorista','role'=>'driver','active'=>true]); return [$fuel,$vehicle,$driver]; }
 private function fueling(User $actor, Vehicle $vehicle, FuelType $fuel, Person $driver, int $number, bool $directDriver=true): Fueling { $request=FuelRequest::create(['request_number'=>$number,'requested_at'=>now()->subDays($number),'vehicle_id'=>$vehicle->id,'driver_person_id'=>$driver->id,'fuel_type_id'=>$fuel->id,'odometer'=>1000+$number,'status'=>'fulfilled','created_by_user_id'=>$actor->id]); return Fueling::create(['fueling_at'=>now()->subDays($number),'request_id'=>$request->id,'vehicle_id'=>$vehicle->id,'driver_person_id'=>$directDriver?$driver->id:null,'fuel_type_id'=>$fuel->id,'odometer'=>1010+$number,'liters'=>20,'unit_price'=>5.5,'total_amount'=>110,'created_by_user_id'=>$actor->id]); }
 public function test_report_handles_empty_second_page_without_500(): void { $actor=$this->actor(); [$fuel,$vehicle,$driver]=$this->context($actor); $this->fueling($actor,$vehicle,$fuel,$driver,1); $this->actingAs($actor,'ldap')->get('/relatorios?page=2')->assertOk()->assertSee('20,000 L'); }
 public function test_driver_filter_uses_legacy_request_driver_when_fueling_driver_is_null(): void { $actor=$this->actor(); [$fuel,$vehicle,$driver]=$this->context($actor); $this->fueling($actor,$vehicle,$fuel,$driver,1,false); $this->actingAs($actor,'ldap')->get('/relatorios?driver_person_id='.$driver->id)->assertOk()->assertSee('20,000 L')->assertSee('Motorista'); }
 public function test_authenticated_user_downloads_a4_pdf_and_opens_receipt(): void { $actor=$this->actor(); [$fuel,$vehicle,$driver]=$this->context($actor); $fueling=$this->fueling($actor,$vehicle,$fuel,$driver,1); $this->actingAs($actor,'ldap')->get('/relatorios/pdf')->assertOk()->assertHeader('content-type','application/pdf'); $this->actingAs($actor,'ldap')->get("/abastecimentos/{$fueling->id}/comprovante")->assertOk()->assertSee('COMPROVANTE INTERNO'); }
 public function test_report_shows_responsible_filter_and_request_driver_fallback(): void { $actor=$this->actor(); [$fuel,$vehicle,$driver]=$this->context($actor); $request=FuelRequest::create(['request_number'=>403,'requested_at'=>now()->subDay(),'vehicle_id'=>$vehicle->id,'driver_person_id'=>$driver->id,'fuel_type_id'=>$fuel->id,'responsible_sector'=>'Gabinete da Presidência','odometer'=>1000,'status'=>'fulfilled','created_by_user_id'=>$actor->id]); Fueling::create(['fueling_at'=>now()->subDay(),'request_id'=>$request->id,'vehicle_id'=>$vehicle->id,'driver_person_id'=>null,'fuel_type_id'=>$fuel->id,'odometer'=>1010,'liters'=>20,'unit_price'=>5.5,'total_amount'=>110,'created_by_user_id'=>$actor->id]); $this->actingAs($actor,'ldap')->get('/relatorios?responsible='.urlencode('Gabinete da Presidência'))->assertOk()->assertSee('Gabinete da Presidência')->assertSee('Motorista')->assertSee('#403'); $this->actingAs($actor,'ldap')->get('/relatorios/pdf?responsible='.urlencode('Gabinete da Presidência'))->assertOk()->assertHeader('content-type','application/pdf'); }
 public function test_responsible_filter_restricts_report_to_selected_sector(): void { $actor=$this->actor(); [$fuel,$vehicle,$driver]=$this->context($actor); $selected=FuelRequest::create(['request_number'=>401,'requested_at'=>now()->subDay(),'vehicle_id'=>$vehicle->id,'driver_person_id'=>$driver->id,'fuel_type_id'=>$fuel->id,'responsible_sector'=>'Gabinete da Presidência','odometer'=>1000,'status'=>'fulfilled','created_by_user_id'=>$actor->id]); $other=FuelRequest::create(['request_number'=>402,'requested_at'=>now()->subDay(),'vehicle_id'=>$vehicle->id,'driver_person_id'=>$driver->id,'fuel_type_id'=>$fuel->id,'responsible_sector'=>'Setor de Obras','odometer'=>1001,'status'=>'fulfilled','created_by_user_id'=>$actor->id]); Fueling::create(['fueling_at'=>now()->subDay(),'request_id'=>$selected->id,'vehicle_id'=>$vehicle->id,'driver_person_id'=>$driver->id,'fuel_type_id'=>$fuel->id,'odometer'=>1010,'liters'=>20,'unit_price'=>5.5,'total_amount'=>110,'created_by_user_id'=>$actor->id]); Fueling::create(['fueling_at'=>now()->subDay()->addMinute(),'request_id'=>$other->id,'vehicle_id'=>$vehicle->id,'driver_person_id'=>$driver->id,'fuel_type_id'=>$fuel->id,'odometer'=>1011,'liters'=>30,'unit_price'=>5.5,'total_amount'=>165,'created_by_user_id'=>$actor->id]); $this->actingAs($actor,'ldap')->get('/relatorios?responsible='.urlencode('Gabinete da Presidência'))->assertOk()->assertSee('Gabinete da Presidência')->assertSee('#401')->assertDontSee('#402')->assertSee('20,000 L'); }
}
