<?php
namespace Tests\Feature;
use App\Models\FuelRequest; use App\Models\FuelType; use App\Models\Fueling; use App\Models\Person; use App\Models\User; use App\Models\Vehicle; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class TwoCopyA4DocumentTest extends TestCase { use RefreshDatabase;
 private function actor(): User { return User::create(['name'=>'Supervisor','username'=>'a4'.uniqid(),'password'=>'SenhaLocal!12345','auth_source'=>'local','role'=>'supervisor','is_active'=>true]); }
 private function request(User $actor,string $status='approved'): FuelRequest { $fuel=FuelType::create(['name'=>'Gasolina','abbreviation'=>'GAS','active'=>true]); $vehicle=Vehicle::create(['plate'=>'ABC1D23','model'=>'Teste','fuel_type_id'=>$fuel->id,'current_odometer'=>1000,'status'=>'active','maintenance_interval_km'=>10000,'maintenance_interval_days'=>180]); $driver=Person::create(['full_name'=>'Motorista','role'=>'driver','active'=>true]); return FuelRequest::create(['request_number'=>123,'requested_at'=>now(),'vehicle_id'=>$vehicle->id,'driver_person_id'=>$driver->id,'fuel_type_id'=>$fuel->id,'odometer'=>1000,'status'=>$status,'created_by_user_id'=>$actor->id]); }
 public function test_authenticated_user_prints_two_copy_a4_for_unfulfilled_request(): void { $actor=$this->actor(); $request=$this->request($actor); $this->actingAs($actor,'ldap')->get("/requisicoes/{$request->id}/comprovante-a4")->assertOk()->assertSee('Via da Frota')->assertSee('Via do Responsável')->assertSee('Abastecimento ainda não registrado'); }
 public function test_authenticated_user_prints_two_copy_a4_with_fueling_data(): void { $actor=$this->actor(); $request=$this->request($actor,'fulfilled'); Fueling::create(['fueling_at'=>now(),'request_id'=>$request->id,'vehicle_id'=>$request->vehicle_id,'driver_person_id'=>$request->driver_person_id,'fuel_type_id'=>$request->fuel_type_id,'odometer'=>1010,'liters'=>20,'unit_price'=>5.5,'total_amount'=>110,'created_by_user_id'=>$actor->id]); $this->actingAs($actor,'ldap')->get("/requisicoes/{$request->id}/comprovante-a4")->assertOk()->assertSee('Dados do abastecimento')->assertSee('R$ 110,00'); }
}
