<?php
namespace Tests\Feature;
use App\Models\FuelType; use App\Models\Person; use App\Models\User; use App\Models\Vehicle; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class VehicleResponsibilityTest extends TestCase { use RefreshDatabase;
 private function supervisor(): User { return User::create(['name'=>'Supervisor','username'=>'sup'.uniqid(),'password'=>'SenhaLocal!12345','auth_source'=>'local','role'=>'supervisor','is_active'=>true]); }
 private function vehicle(): Vehicle { $fuel=FuelType::create(['name'=>'Gasolina','abbreviation'=>'GAS','active'=>true]);return Vehicle::create(['plate'=>'ABC1D23','model'=>'Teste','fuel_type_id'=>$fuel->id,'current_odometer'=>100,'status'=>'active','maintenance_interval_km'=>10000,'maintenance_interval_days'=>180]); }
 public function test_supervisor_registers_shared_sectors_with_history(): void { $actor=$this->supervisor();$vehicle=$this->vehicle();$council=Person::create(['full_name'=>'Vereador Teste','role'=>'council_member','active'=>true]);$this->actingAs($actor,'ldap')->put("/cadastros/veiculos/{$vehicle->id}/responsaveis",['council_member_id'=>$council->id,'sectors'=>"Transporte\nTV Câmara"])->assertRedirect();$this->assertDatabaseCount('vehicle_responsibilities',3);$this->assertDatabaseHas('vehicle_responsibilities',['vehicle_id'=>$vehicle->id,'responsibility_type'=>'sector','sector'=>'Transporte','ended_at'=>null]);$this->assertDatabaseHas('vehicle_responsibilities',['vehicle_id'=>$vehicle->id,'responsibility_type'=>'sector','sector'=>'TV Câmara','ended_at'=>null]); }
 public function test_maintenance_checkbox_blocks_vehicle_from_new_request_options(): void { $actor=$this->supervisor();$vehicle=$this->vehicle();$payload=['plate'=>$vehicle->plate,'model'=>$vehicle->model,'fuel_type_id'=>$vehicle->fuel_type_id,'current_odometer'=>100,'status'=>'active','maintenance_mode'=>'1','maintenance_interval_km'=>10000,'maintenance_interval_days'=>180];$this->actingAs($actor,'ldap')->put("/cadastros/veiculos/{$vehicle->id}",$payload)->assertRedirect('/cadastros/veiculos');$this->assertDatabaseHas('vehicles',['id'=>$vehicle->id,'status'=>'maintenance']);$this->actingAs($actor,'ldap')->get('/requisicoes/nova')->assertDontSee($vehicle->plate); }
}
