<?php
namespace Tests\Feature;
use App\Models\FuelRequest; use App\Models\FuelType; use App\Models\Fueling; use App\Models\User; use App\Models\Vehicle; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class VehicleStatusFiltersTest extends TestCase { use RefreshDatabase;
 private function user(): User { return User::create(['name'=>'Supervisor','username'=>'status'.uniqid(),'password'=>'SenhaLocal!12345','auth_source'=>'local','role'=>'supervisor','is_active'=>true]); }
 private function vehicle(string $plate,string $status): Vehicle { $fuel=FuelType::firstOrCreate(['name'=>'Gasolina'],['abbreviation'=>'GAS','active'=>true]);return Vehicle::create(['plate'=>$plate,'model'=>$status,'fuel_type_id'=>$fuel->id,'current_odometer'=>100,'status'=>$status,'maintenance_interval_km'=>10000,'maintenance_interval_days'=>180]); }
 public function test_vehicle_registry_defaults_to_active_and_all_filter_restores_history(): void { $user=$this->user();$this->vehicle('ACT1V01','active');$this->vehicle('INA1V01','inactive');$this->actingAs($user,'ldap')->get('/cadastros/veiculos')->assertSee('ACT1V01')->assertDontSee('INA1V01');$this->actingAs($user,'ldap')->get('/cadastros/veiculos?vehicle_status=all')->assertSee('ACT1V01')->assertSee('INA1V01'); }
 public function test_operational_lists_and_report_filter_by_current_vehicle_status(): void { $user=$this->user();$active=$this->vehicle('ATV1S01','active');$inactive=$this->vehicle('INT1S01','inactive');$fuel=FuelType::first();foreach([[$active,701],[$inactive,702]] as [$vehicle,$number]){$request=FuelRequest::create(['request_number'=>$number,'requested_at'=>now(),'vehicle_id'=>$vehicle->id,'fuel_type_id'=>$fuel->id,'odometer'=>100,'status'=>'fulfilled','created_by_user_id'=>$user->id]);Fueling::create(['fueling_at'=>now(),'request_id'=>$request->id,'vehicle_id'=>$vehicle->id,'fuel_type_id'=>$fuel->id,'odometer'=>110,'liters'=>10,'unit_price'=>5,'total_amount'=>50,'created_by_user_id'=>$user->id]);}$this->actingAs($user,'ldap')->get('/requisicoes')->assertSee('#701')->assertDontSee('#702');$this->actingAs($user,'ldap')->get('/abastecimentos?vehicle_status=inactive')->assertSee('INT1S01')->assertDontSee('ATV1S01');$this->actingAs($user,'ldap')->get('/relatorios?vehicle_status=inactive')->assertSee('INT1S01')->assertDontSee('ATV1S01'); }
}
