@extends('layouts.app',['title'=>'Abastecimentos · Frota Câmara'])
@section('content')<p class="page-kicker">Execução da requisição</p><h1>Abastecimentos</h1><p class="lede">Os documentos abrem em nova aba para preservar a posição atual desta lista e facilitar a impressão.</p><section class="surface"><form method="get" style="display:flex;gap:10px;align-items:end;flex-wrap:wrap;margin-bottom:16px">@include('components.vehicle-status-filter',['selected'=>$vehicleStatus])<button style="padding:10px 13px;border:0;border-radius:7px;background:#17354f;color:#fff;font-weight:700">Aplicar filtro</button></form><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Data</th><th>Req.</th><th>Responsável</th><th>Veículo</th><th>Litros</th><th>Total</th><th style="text-align:right">Ações</th></tr></thead><tbody>@forelse($items as $f)<tr><td>{{ $f->fueling_at->format('d/m/Y H:i') }}</td><td>#{{ $f->fuelRequest?->request_number }}</td>@php
  $responsible = $f->fuelRequest?->requester?->full_name;
  if (!$responsible) {
      $council = $f->vehicle?->activeResponsibilities?->firstWhere('responsibility_type','council_member');
      $sectors = $f->vehicle?->activeResponsibilities?->where('responsibility_type','sector')->pluck('sector')->filter()->join(' / ');
      $responsible = $council?->person?->full_name ?: ($sectors ?: '—');
  }
@endphp<td>{{ $responsible }}</td><td><span class="vehicle-plate" aria-label="Placa do veículo">{{ $f->vehicle?->plate }}</span></td><td>{{ number_format($f->liters,3,',','.') }}</td><td>R$ {{ number_format($f->total_amount,2,',','.') }}</td><td style="text-align:right;white-space:nowrap"><a href="{{ route('fuelings.receipt',$f) }}" target="_blank" rel="noopener" aria-label="Abrir comprovante térmico do abastecimento {{ $f->id }} em nova aba" style="display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid #b9cac3;border-radius:7px;background:#fff;color:#17354f;font-weight:700">⌑ Cupom 80 mm</a>@if($f->fuelRequest)<a href="{{ route('fuel-requests.a4',$f->fuelRequest) }}" target="_blank" rel="noopener" aria-label="Abrir comprovante A4 em duas vias da requisição {{ $f->fuelRequest->request_number }}" style="display:inline-flex;align-items:center;gap:7px;margin-left:6px;padding:7px 10px;border:1px solid #b9cac3;border-radius:7px;background:#fff;color:#17354f;font-weight:700">A4 · 2 vias</a>@endif</td></tr>@empty<tr><td colspan="7" style="padding:26px;text-align:center">Nenhum abastecimento registrado.</td></tr>@endforelse</tbody></table></div>@include('components.compact-pagination',['paginator'=>$items])</section>@endsection
