@extends('layouts.app',['title'=>'Nova manutenção · Frota Câmara'])
@section('content')<div class="maintenance-heading" style="display:flex;align-items:flex-start;justify-content:space-between;gap:24px;flex-wrap:wrap;margin-bottom:12px"><div><p class="page-kicker">Registro de manutenção</p><h1>Nova manutenção</h1></div><div style="margin-left:auto"><div id="maintenance-plate-header" class="vehicle-plate-preview" aria-live="polite" hidden><span class="vehicle-plate" aria-label="Placa do veículo" style="position:relative;display:inline-flex;flex-direction:column;align-items:center;justify-content:flex-end;width:190px;min-width:190px;min-height:85px;padding:30px 10px 9px;border:6px solid #050505;border-radius:11px;background:#ededed;box-shadow:inset 0 0 0 3px #c6c6c6,0 3px 7px rgba(0,0,0,.18);color:#050505;font-family:Arial Black,Arial,Helvetica,sans-serif;font-size:31px;font-weight:900;letter-spacing:1.5px;line-height:1;text-align:center;white-space:nowrap;overflow:hidden;box-sizing:border-box"><span id="maintenance-plate-title" aria-hidden="true" style="position:absolute;top:5px;left:0;right:0;color:#171db3;font-family:Arial,Helvetica,sans-serif;font-size:16px;font-weight:900;letter-spacing:1.5px;line-height:1;text-align:center">CMRP</span><span id="maintenance-plate-value" style="display:block;line-height:1"></span></span><small id="maintenance-plate-description" hidden aria-hidden="true"></small></div></div></div><section class="surface"><form method="post" action="{{ route('maintenance.store') }}" class="form-grid" style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px">@csrf
<label><strong>Veículo</strong><select name="vehicle_id">@foreach($vehicles as $v)<option value="{{ $v->id }}" data-plate="{{ $v->plate }}">{{ $v->plate }} · {{ $v->model }}</option>@endforeach</select></label>

@foreach(['service_type'=>'Tipo de serviço','performed_at'=>'Data','odometer'=>'Hodômetro','cost'=>'Custo','next_maintenance_at'=>'Próxima data','next_maintenance_odometer'=>'Próximo hodômetro','provider'=>'Fornecedor'] as $field=>$label)<label style="display:grid;gap:6px"><strong>{{ $label }}</strong><input type="{{ in_array($field,['performed_at','next_maintenance_at'])?'datetime-local':(in_array($field,['odometer','cost','next_maintenance_odometer'])?'number':'text') }}" name="{{ $field }}" value="{{ old($field,$field==='performed_at'?now()->format('Y-m-d\TH:i'):'') }}" step="{{ $field==='cost'?'0.01':'1' }}">@error($field)<small style="color:#b42318">{{ $message }}</small>@enderror</label>@endforeach
<label style="grid-column:1/-1;display:grid;gap:6px"><strong>Observações</strong><textarea name="notes" rows="3"></textarea></label><div style="grid-column:1/-1"><button style="padding:11px 16px;background:#1f6a60;border:0;border-radius:7px;color:#fff;font-weight:700">Registrar manutenção</button></div></form></section>
<script>
document.addEventListener('DOMContentLoaded',function(){
 const select=document.querySelector('select[name="vehicle_id"]'),preview=document.getElementById('maintenance-plate-header'),value=document.getElementById('maintenance-plate-value'),description=document.getElementById('maintenance-plate-description');
 function syncMaintenancePlate(){const option=select?.options?.[select.selectedIndex],plate=option?.dataset?.plate ?? '',label=option?.textContent?.trim() ?? '';preview.hidden=!plate;value.textContent=plate;description.textContent=plate ? 'Veículo selecionado: '+label : 'Placa do veículo selecionado';}
 if(select){select.addEventListener('change',syncMaintenancePlate);syncMaintenancePlate();}
});
</script>
@endsection
