<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void { $cutoff='2025-01-01 00:00:00'; $driver=DB::connection()->getDriverName(); $hasAt=Schema::hasColumn('fuel_requests','authorization_at'); $hasExpiry=Schema::hasColumn('fuel_requests','authorization_expires_at'); if(!$hasAt || !$hasExpiry){Schema::table('fuel_requests',function(Blueprint $table) use($hasAt,$hasExpiry){if(!$hasAt)$table->dateTime('authorization_at')->nullable()->after('approved_at');if(!$hasExpiry)$table->dateTime('authorization_expires_at')->nullable()->after($hasAt?'authorization_at':'approved_at');});} if($driver==='mysql'){DB::statement('ALTER TABLE fuel_requests MODIFY authorization_at DATETIME NULL, MODIFY authorization_expires_at DATETIME NULL'); $indexExists=DB::select("SHOW INDEX FROM fuel_requests WHERE Key_name='fuel_requests_authorization_expiry_idx'"); if(count($indexExists)===0)Schema::table('fuel_requests',function(Blueprint $table){$table->index('authorization_expires_at','fuel_requests_authorization_expiry_idx');});}else{Schema::table('fuel_requests',function(Blueprint $table){$table->index('authorization_expires_at','fuel_requests_authorization_expiry_idx');});} DB::table('fuel_requests')->where('requested_at','<',$cutoff)->update(['authorization_at'=>null,'authorization_expires_at'=>null]); DB::table('fuel_requests')->where('requested_at','>=',$cutoff)->select(['id','approved_at','requested_at','authorization_at','authorization_expires_at'])->orderBy('id')->lazyById(250,'id')->each(function(object $request):void{$base=$request->approved_at ?? $request->requested_at; if($base===null)return; $authorizedAt=\Carbon\Carbon::parse($request->authorization_at ?? $base); $expiresAt=$request->authorization_expires_at!==null?\Carbon\Carbon::parse($request->authorization_expires_at):\Carbon\Carbon::parse($base)->addDays(3); DB::table('fuel_requests')->where('id',$request->id)->update(['authorization_at'=>$authorizedAt->format('Y-m-d H:i:s'),'authorization_expires_at'=>$expiresAt->format('Y-m-d H:i:s')]);}); }
 public function down(): void { /* Migração deliberadamente não destrutiva: não remover dados de autorização de requisições históricas. */ }
};
