<?php

return [
    'items' => [
        'dashboard' => [
            'label' => 'Painel',
            'symbol' => '01',
            'route' => 'dashboard',
            'pattern' => 'dashboard',
            'section' => 'Operação',
            'roles' => ['user', 'supervisor', 'admin'],
            'default' => true,
            'configurable' => true,
        ],
        'requests' => [
            'label' => 'Requisições',
            'symbol' => '02',
            'route' => 'fuel-requests.index',
            'pattern' => 'fuel-requests.*',
            'section' => 'Operação',
            'roles' => ['user', 'supervisor', 'admin'],
            'default' => true,
            'configurable' => true,
        ],
        'fuelings' => [
            'label' => 'Abastecimentos',
            'symbol' => '03',
            'route' => 'fuelings.index',
            'pattern' => 'fuelings.*',
            'section' => 'Operação',
            'roles' => ['user', 'supervisor', 'admin'],
            'default' => true,
            'configurable' => true,
        ],
        'maintenance' => [
            'label' => 'Manutenções',
            'symbol' => '04',
            'route' => 'maintenance.index',
            'pattern' => 'maintenance.*',
            'section' => 'Operação',
            'roles' => ['user', 'supervisor', 'admin'],
            'default' => true,
            'configurable' => true,
        ],
        'reports' => [
            'label' => 'Relatórios',
            'symbol' => '05',
            'route' => 'reports.index',
            'pattern' => 'reports.*',
            'section' => 'Operação',
            'roles' => ['user', 'supervisor', 'admin'],
            'default' => true,
            'configurable' => true,
        ],
        'master-data' => [
            'label' => 'Cadastros',
            'symbol' => '06',
            'route' => 'master-data.index',
            'pattern' => 'master-data.*',
            'section' => 'Operação',
            'roles' => ['supervisor'],
            'default' => true,
            'configurable' => true,
        ],
        'indicators' => [
            'label' => 'Indicadores',
            'symbol' => '07',
            'route' => 'indicators.index',
            'pattern' => 'indicators.*',
            'section' => 'Operação',
            'roles' => ['user', 'supervisor', 'admin'],
            'default' => true,
            'configurable' => true,
        ],
        'menu-settings' => [
            'label' => 'Configuração do menu',
            'symbol' => '08',
            'route' => 'menu-settings.index',
            'pattern' => 'menu-settings.*',
            'section' => 'Administração',
            'roles' => ['admin'],
            'default' => true,
            'configurable' => false,
            'always_visible' => true,
        ],
    ],
];
