<section class="manual-grid">
  <article class="manual-card"><h2>1. Início do turno</h2><p>Entre com seu <strong>USUÁRIO DE REDE</strong> e confirme identidade, perfil Operador, conexão HTTPS e situação das pendências. Revise requisições enviadas, autorizações próximas do vencimento e registros que aguardam conferência.</p></article>
  <article class="manual-card"><h2>2. Analisar e decidir</h2><ol><li>Confira número, data, veículo, placa, combustível, hodômetro e Gabinete/Setor.</li><li>Verifique se a necessidade está descrita e se o veículo está disponível.</li><li>Aprove somente após conferir todos os dados.</li><li>Rejeite com motivo objetivo quando a solicitação não puder ser atendida.</li></ol></article>
  <article class="manual-card"><h2>3. Abastecer</h2><p>Registre somente requisição aprovada. Informe data e hora reais, hodômetro, litros, preço praticado, documento, posto e motorista. Confirme o total e evite duplo clique se a resposta demorar.</p></article>
</section>
<section class="manual-section"><h2>Autorizações e impressão</h2><table class="manual-table"><thead><tr><th>Botão</th><th>Uso</th></tr></thead><tbody><tr><td><strong>Autorização - 3 vias A4</strong></td><td>Documento em papel A4 para Posto, Motorista e CMRP.</td></tr><tr><td><strong>Autorização - 3 vias Cupom</strong></td><td>Documento térmico para rolo de 80 mm da Epson T20.</td></tr></tbody></table><p>Confira a validade de três dias quando aplicável. Na Epson T20, selecione rolo de 80 mm e escala padrão na janela do navegador.</p></section>
<section class="manual-section"><h2>Configuração de impressão A4</h2><ol><li>Abra o relatório PDF A4 ou o documento A4 em nova aba.</li><li>Selecione a impressora A4 institucional, papel A4, orientação Retrato e escala 100%.</li><li>Confira a pré-visualização e confirme que as linhas de assinatura não foram cortadas.</li></ol></section>
<section class="manual-section"><h2>Disponibilidade de veículos e filtros</h2><p>As listas operacionais iniciam com veículos ativos. Use o filtro <strong>Situação do veículo</strong> para consultar veículos indisponíveis, inativos ou todo o histórico conforme a necessidade da operação.</p></section>
<section class="manual-section"><h2>Relatórios</h2><p>Use situação do veículo, veículo, motorista, <strong>Gabinete/Setor</strong>, data inicial e data final. O filtro por Gabinete/Setor considera o valor da requisição e o responsável vinculado. O PDF A4 leva os filtros ao cabeçalho e mostra o motorista do abastecimento ou da requisição vinculada.</p></section>
<section class="manual-section"><h2>Configuração de impressora térmica 80 mm</h2><ol><li>Selecione a Epson T20 na janela do navegador.</li><li>Use papel Roll Paper 80 × 297 mm, escala 100% e margens compatíveis com o driver.</li><li>Faça um teste e confira largura, cabeçalho, valores e a linha de corte.</li></ol></section>
<section class="manual-section"><h2>Veículos e manutenção</h2><p>Confira a situação cadastral, os responsáveis, os intervalos e os registros do veículo. Um veículo indisponível não deve ser utilizado em nova requisição. Registre alterações de forma coerente com a situação real e preserve o histórico.</p></section>
<section class="manual-section"><h2>Falhas e suporte</h2><ul><li>Erro 403: confirme o perfil e o grupo AD; não tente contornar a autorização.</li><li>Erro 500: registre horário, tela, endereço e número da requisição; acione a TI para consultar logs.</li><li>PDF ou cupom: confirme HTTPS, navegador, impressora e papel de 80 mm.</li><li>Não altere `.env`, permissões amplas ou dados históricos sem procedimento técnico.</li></ul></section>
