<section class="manual-grid">
  <article class="manual-card"><h2>1. Acesso técnico</h2><p>Acesse o sistema pelo domínio HTTPS institucional. A Administração técnica não substitui a decisão operacional: não aprova requisições nem registra abastecimentos em nome de terceiros.</p></article>
  <article class="manual-card"><h2>2. Controle de perfis</h2><p>Usuário cria e acompanha requisições; Operador analisa, aprova, registra abastecimentos e mantém a operação; Administração técnica administra acesso, infraestrutura, menu, logs e suporte.</p></article>
  <article class="manual-card"><h2>3. Configuração do menu</h2><p>Abra <strong>Configuração do menu</strong> para habilitar ou ocultar itens para Usuário e Operador. A alteração controla a visibilidade do atalho; as rotas continuam protegidas por papel.</p></article>
</section>
<section class="manual-section"><h2>HTTPS e rede interna</h2><ol><li>O endereço oficial é <strong>https://frota.camararibeiraopreto.sp.gov.br</strong>.</li><li>O certificado é emitido pela Autoridade de Certificação interna da Câmara para o nome DNS.</li><li>A rede cabeada resolve o domínio para a VM da Frota e permite a porta 443.</li><li>Se a Wi-Fi não resolver o domínio, acione a infraestrutura de rede; não use certificado desconhecido nem contorne o domínio pelo IP.</li></ol></section>
<section class="manual-section"><h2>Operação segura</h2><ul><li>Faça backup antes de migrations, alterações de Nginx, Laravel ou permissões.</li><li>Não use `chmod 777` e não exponha `.env`, cookies, tokens ou chaves privadas.</li><li>O código deve ser legível pelo PHP-FPM; a chave HTTPS deve permanecer protegida em `root:root`.</li><li>Após alterações, use `php artisan optimize:clear`, valide `nginx -t` quando aplicável e registre o resultado.</li></ul></section>
<section class="manual-section"><h2>Relatórios e documentos</h2><p>O relatório A4 informa o Gabinete/Setor aplicado e usa o motorista do abastecimento ou, como fallback, o motorista da requisição. A autorização A4 e o cupom Epson T20 devem ser testados pelo navegador em HTTPS.</p></section>
<section class="manual-section"><h2>Diagnóstico</h2><table class="manual-table"><thead><tr><th>Sintoma</th><th>Verificação</th></tr></thead><tbody><tr><td>HTTP 500</td><td>Consultar o erro mais recente do Laravel e verificar permissões de leitura do PHP-FPM.</td></tr><tr><td>HTTP 419</td><td>Confirmar sessão, HTTPS, cookie seguro e o isolamento CSRF da suíte de testes.</td></tr><tr><td>Download inseguro</td><td>Confirmar que página e PDF usam HTTPS e que o APP_URL está seguro.</td></tr><tr><td>Menu ausente</td><td>Verificar o perfil, a configuração em Configuração do menu e os caches compilados.</td></tr><tr><td>DNS indisponível</td><td>Verificar o registro interno e a rota da rede antes de alterar a aplicação.</td></tr></tbody></table></section>
<section class="manual-section"><h2>Suporte técnico</h2><p>Registre data, hora, host, usuário, URL, perfil, ação, mensagem visível e último resultado de teste. Não anexe cookies, senhas, chaves, `.env` ou dumps com dados sensíveis.</p></section>
