<section class="manual-grid">
  <article class="manual-card"><h2>1. Acesso</h2><p>Acesse <strong>https://frota.camararibeiraopreto.sp.gov.br</strong> pela rede institucional autorizada. Use sua identidade corporativa e confirme o perfil exibido. Se houver alerta de certificado ou perfil incorreto, encerre a sessão e acione a TI.</p></article>
  <article class="manual-card"><h2>2. Criar requisição</h2><ol><li>Abra <strong>Nova requisição</strong>.</li><li>Selecione veículo, combustível e informe o hodômetro.</li><li>Revise placa, Gabinete/Setor e observação.</li><li>Salve o rascunho ou use <strong>Enviar</strong> quando os dados estiverem completos.</li></ol></article>
  <article class="manual-card"><h2>3. Acompanhar</h2><p>Consulte a situação da requisição: rascunho, enviada, aprovada, rejeitada, cancelada ou concluída. Não duplique solicitações e não altere o histórico.</p></article>
</section>
<section class="manual-section"><h2>Autorização em três vias</h2><p>Após a aprovação, a autorização pode ser emitida em três vias, destinadas ao Posto, ao Motorista e à CMRP, com validade de três dias quando aplicável.</p><ol><li>Use <strong>Autorização - 3 vias A4</strong> para papel A4.</li><li>Use <strong>Autorização - 3 vias Cupom</strong> para a Epson T20 em rolo de 80 mm.</li><li>Na impressão, confirme a impressora e a pré-visualização antes de concluir.</li></ol></section>
<section class="manual-section"><h2>Configuração de impressão A4</h2><ol><li>Abra o relatório PDF A4 em nova aba.</li><li>Selecione a impressora institucional, papel A4, orientação Retrato e escala 100%.</li><li>Confira a pré-visualização antes de imprimir.</li></ol></section>
<section class="manual-section"><h2>Disponibilidade de veículos e filtros</h2><p>Use os filtros disponíveis para consultar registros conforme o período, veículo, motorista e Gabinete/Setor. Se o veículo não estiver disponível para uma nova solicitação, informe o Operador ou a TI.</p></section>
<section class="manual-section"><h2>Relatórios</h2><p>Em <strong>Relatórios</strong>, filtre por veículo, motorista, Gabinete/Setor e período. O PDF A4 preserva os filtros. O cabeçalho mostra o Gabinete/Setor escolhido ou “Sem filtro”; a coluna Motorista utiliza o abastecimento e, se necessário, a requisição vinculada.</p></section>
<section class="manual-section"><h2>Segurança e suporte</h2><ul><li>Não compartilhe senha, cookie, chave de certificado ou conteúdo do `.env`.</li><li>Use o domínio HTTPS, não o IP, para acessar o sistema.</li><li>Em caso de erro 403 ou 500, registre horário, tela e número da requisição e acione a TI.</li><li>Ao terminar, encerre a sessão em estações compartilhadas.</li></ul></section>
