<?php
namespace App\Http\Controllers;
use App\Models\FuelRequest; use App\Models\Fueling; use App\Models\FuelType; use App\Models\MaintenanceRecord; use App\Models\Person; use App\Models\User; use App\Models\Vehicle; use App\Services\FuelingService; use App\Services\FuelRequestService; use App\Services\MaintenanceService; use App\Services\OperationalPermissionException; use App\Services\OperationalStateException; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\DB; use Illuminate\View\View;
class OperationsController extends Controller
{
 private const STATUSES=['draft'=>'Rascunho','submitted'=>'Enviada','approved'=>'Aprovada','rejected'=>'Rejeitada','canceled'=>'Cancelada','fulfilled'=>'Cumprida'];
 public function requests(Request $request): View { $user=$this->user($request);$vehicleStatus=$this->vehicleStatus($request);$requestStatus=(string)$request->query('request_status','');if($requestStatus!==''&&!array_key_exists($requestStatus,self::STATUSES))$requestStatus='';$query=$this->statusScope(FuelRequest::with(['vehicle','fuelType','requester','driver','approver','fueling']),$vehicleStatus);if($requestStatus!=='')$query->where('status',$requestStatus);$items=$query->latest('id')->paginate(20)->withQueryString();return view('operations.requests-index',compact('user','items','vehicleStatus','requestStatus')+['guard'=>$request->attributes->get('fleet.guard'),'statuses'=>self::STATUSES]); }
 public function requestCreate(Request $request): View { $user=$this->operationalUser($request);$vehicles=Vehicle::query()->where('status','active')->with(['fuelType','activeResponsibilities.person'])->orderBy('plate')->get();$referencePrices=DB::table('valorcomb')->where('effective_at','<=',now())->orderByDesc('effective_at')->get()->unique('fuel_type_id')->mapWithKeys(fn($price)=>[(string)$price->fuel_type_id=>['value'=>(float)$price->valorcomb,'effective_at'=>\Carbon\Carbon::parse($price->effective_at)->format('d/m/Y')]])->all();return view('operations.request-form',['vehicles'=>$vehicles,'fuelTypes'=>FuelType::query()->where('active',true)->orderBy('name')->get(),'councilMembers'=>Person::query()->where('active',true)->where('role','council_member')->orderBy('full_name')->get(),'referencePrices'=>$referencePrices,'user'=>$user,'guard'=>$request->attributes->get('fleet.guard')]); }
 public function requestStore(Request $request,FuelRequestService $service): RedirectResponse { $user=$this->operationalUser($request);$data=$request->validate($this->requestRules());$vehicle=Vehicle::query()->with('activeResponsibilities.person')->findOrFail($data['vehicle_id']);$council=$vehicle->activeResponsibilities->first(fn($item)=>$item->responsibility_type==='council_member'&&$item->person?->role==='council_member'&&$item->person?->active);$sectors=$vehicle->activeResponsibilities->where('responsibility_type','sector')->pluck('sector')->filter()->values();$sector=trim((string)($data['responsible_sector']??''));if($council!==null){$data['requester_person_id']=$council->person_id;$data['responsible_sector']=null;}elseif($sectors->count()===1){$data['requester_person_id']=null;$data['responsible_sector']=$sectors->first();}elseif($sectors->count()>1){$data['requester_person_id']=null;$data['responsible_sector']=$sector!==''?$sector:null;if(empty($data['responsible_sector'])||!$sectors->contains($data['responsible_sector']))return back()->withErrors(['responsible_sector'=>'Selecione um dos setores responsáveis vinculados ao veículo.'])->withInput();}else{return back()->withErrors(['requester_person_id'=>'O veículo não possui vereador ou setor responsável vinculado.'])->withInput();}try { $record=$service->createDraft($user,$data); return redirect()->route('fuel-requests.show',$record)->with('status',"Requisição nº {$record->request_number} criada como rascunho."); } catch(OperationalStateException|OperationalPermissionException $e) { return back()->withErrors(['operation'=>$e->getMessage()])->withInput(); } }
 public function requestShow(Request $request,FuelRequest $fuelRequest): View { $user=$this->user($request); $fuelRequest->load(['vehicle','fuelType','requester','driver','approver','creator','fueling']); return view('operations.request-show',compact('user','fuelRequest')+['guard'=>$request->attributes->get('fleet.guard'),'statuses'=>self::STATUSES]); }
 public function requestSubmit(Request $request,FuelRequest $fuelRequest,FuelRequestService $service): RedirectResponse { return $this->requestAction($request,$fuelRequest,fn(User $u)=>$service->submit($u,$fuelRequest->id),'Requisição enviada para supervisão.'); }
 public function requestApprove(Request $request,FuelRequest $fuelRequest,FuelRequestService $service): RedirectResponse { $this->supervisor($request); return $this->requestAction($request,$fuelRequest,fn(User $u)=>$service->approve($u,$fuelRequest->id),'Requisição aprovada e autorizada por três dias corridos.'); }
 public function requestReject(Request $request,FuelRequest $fuelRequest,FuelRequestService $service): RedirectResponse { $this->supervisor($request); $reason=$request->validate(['rejection_reason'=>['required','string','max:1000']])['rejection_reason']; return $this->requestAction($request,$fuelRequest,fn(User $u)=>$service->reject($u,$fuelRequest->id,$reason),'Requisição rejeitada.'); }
 public function requestCancel(Request $request,FuelRequest $fuelRequest,FuelRequestService $service): RedirectResponse { return $this->requestAction($request,$fuelRequest,fn(User $u)=>$service->cancel($u,$fuelRequest->id),'Requisição cancelada.'); }
 private function requestAction(Request $request,FuelRequest $fuelRequest,callable $action,string $success): RedirectResponse { $user=$this->user($request); try{$action($user);return back()->with('status',$success);}catch(OperationalStateException|OperationalPermissionException $e){return back()->withErrors(['operation'=>$e->getMessage()]);} }
 public function fuelings(Request $request): View { $user=$this->user($request);$vehicleStatus=$this->vehicleStatus($request);$items=$this->statusScope(Fueling::with(['fuelRequest.requester','vehicle.activeResponsibilities.person','fuelType','driver','creator']),$vehicleStatus)->latest('fueling_at')->paginate(20)->withQueryString();return view('operations.fuelings-index',compact('user','items','vehicleStatus')+['guard'=>$request->attributes->get('fleet.guard')]); }
 public function fuelingCreate(Request $request,FuelRequest $fuelRequest): View { $user=$this->supervisor($request); if($fuelRequest->status!=='approved') abort(422,'Somente requisições aprovadas podem ser cumpridas.'); if($fuelRequest->requiresAuthorization() && !$fuelRequest->hasActiveAuthorization()) abort(422,'A autorização desta requisição expirou. Solicite nova autorização.'); $fuelRequest->load(['vehicle','fuelType','driver']); return view('operations.fueling-form',compact('user','fuelRequest')+$this->options($request)+['guard'=>$request->attributes->get('fleet.guard')]); }
 public function fuelingStore(Request $request,FuelRequest $fuelRequest,FuelingService $service): RedirectResponse { $user=$this->supervisor($request); try{$data=$request->validate(['fueling_at'=>['required','date'],'driver_person_id'=>['nullable','exists:people,id'],'odometer'=>['required','integer','min:0'],'liters'=>['required','numeric','gt:0'],'unit_price'=>['required','numeric','min:0'],'invoice_number'=>['nullable','string','max:120'],'station_name'=>['nullable','string','max:180'],'notes'=>['nullable','string','max:2000']]);$data+=['request_id'=>$fuelRequest->id,'vehicle_id'=>$fuelRequest->vehicle_id,'fuel_type_id'=>$fuelRequest->fuel_type_id];$fueling=$service->fulfill($user,$data);return redirect()->route('fuelings.index')->with('status',"Abastecimento nº {$fueling->id} registrado e requisição cumprida.");}catch(OperationalStateException|OperationalPermissionException $e){return back()->withErrors(['operation'=>$e->getMessage()])->withInput();} }
 public function maintenance(Request $request): View { $user=$this->user($request);$vehicleStatus=$this->vehicleStatus($request);$items=$this->statusScope(MaintenanceRecord::with(['vehicle','creator']),$vehicleStatus)->latest('performed_at')->paginate(20)->withQueryString();return view('operations.maintenance-index',compact('user','items','vehicleStatus')+['guard'=>$request->attributes->get('fleet.guard')]); }
 public function maintenanceCreate(Request $request): View { $user=$this->supervisor($request); return view('operations.maintenance-form',$this->options($request)+compact('user')+['guard'=>$request->attributes->get('fleet.guard')]); }
 public function maintenanceStore(Request $request,MaintenanceService $service): RedirectResponse { $user=$this->supervisor($request); try{$data=$request->validate(['vehicle_id'=>['required','exists:vehicles,id'],'service_type'=>['required','string','max:180'],'performed_at'=>['required','date'],'odometer'=>['required','integer','min:0'],'cost'=>['required','numeric','min:0'],'next_maintenance_at'=>['nullable','date'],'next_maintenance_odometer'=>['nullable','integer','min:0'],'provider'=>['nullable','string','max:180'],'notes'=>['nullable','string','max:2000']]);$record=$service->record($user,$data);return redirect()->route('maintenance.index')->with('status',"Manutenção nº {$record->id} registrada.");}catch(OperationalStateException|OperationalPermissionException $e){return back()->withErrors(['operation'=>$e->getMessage()])->withInput();} }
 private function vehicleStatus(Request $request): string {$value=(string)$request->query('vehicle_status','active');return in_array($value,['active','maintenance','inactive','all'],true)?$value:'active';} private function statusScope($query,string $status){return $status==='all'?$query:$query->whereHas('vehicle',fn($vehicleQuery)=>$vehicleQuery->where('status',$status));} private function user(Request $request): User{return $request->attributes->get('fleet.user');} private function operationalUser(Request $request): User{$user=$this->user($request);Gate::forUser($user)->authorize('operate-fleet');return $user;} private function supervisor(Request $request): User{$user=$this->user($request);Gate::forUser($user)->authorize('supervise-fleet');return $user;} private function options(Request $request):array{return['vehicles'=>Vehicle::where('status','active')->orderBy('plate')->get(),'fuelTypes'=>FuelType::where('active',true)->orderBy('name')->get(),'people'=>Person::where('active',true)->orderBy('full_name')->get()];} private function requestRules():array{return['requested_at'=>['required','date'],'vehicle_id'=>['required','exists:vehicles,id'],'requester_person_id'=>['nullable','exists:people,id'],'responsible_sector'=>['nullable','string','max:120'],'driver_person_id'=>['nullable','exists:people,id'],'fuel_type_id'=>['required','exists:fuel_types,id'],'odometer'=>['required','integer','min:0'],'requested_liters'=>['nullable','numeric','min:0'],'estimated_amount'=>['nullable','numeric','min:0'],'notes'=>['nullable','string','max:2000']];}
}
