<?php
namespace App\Http\Controllers;
use App\Models\Fueling; use App\Models\FuelRequest; use App\Models\Person; use App\Models\Vehicle; use Barryvdh\DomPDF\Facade\Pdf; use Carbon\Carbon; use Illuminate\Database\Eloquent\Builder; use Illuminate\Http\Request; use Illuminate\View\View;
class ReportsController extends Controller
{
 public function index(Request $request): View {[$filters,$query]=$this->filteredQuery($request);$totals=(clone $query)->reorder()->selectRaw('COALESCE(SUM(liters),0) as liters, COALESCE(SUM(total_amount),0) as amount')->first();$fuelings=$query->paginate(50)->withQueryString();$vehicles=Vehicle::query()->when(($filters['vehicle_status']??'active')!=='all',fn($vehicleQuery)=>$vehicleQuery->where('status',$filters['vehicle_status']))->orderBy('plate')->get();return view('reports.index',['user'=>$request->attributes->get('fleet.user'),'guard'=>$request->attributes->get('fleet.guard'),'fuelings'=>$fuelings,'filters'=>$filters,'vehicles'=>$vehicles,'drivers'=>Person::where('role','driver')->orderBy('full_name')->get(),'responsibleOptions'=>$this->responsibleOptions(),'totals'=>$totals]);}
 public function pdf(Request $request){[$filters,$query]=$this->filteredQuery($request);$fuelings=$query->get();$totals=['liters'=>$fuelings->sum('liters'),'amount'=>$fuelings->sum('total_amount')];return Pdf::loadView('reports.a4',['fuelings'=>$fuelings,'filters'=>$filters,'totals'=>$totals])->setPaper('a4','portrait')->download('relatorio-abastecimentos-'.now()->format('Ymd-His').'.pdf');}
 public function receipt(Request $request,Fueling $fueling): View {$fueling->load(['fuelRequest','vehicle','driver','fuelType','creator']);return view('reports.receipt',['fueling'=>$fueling,'user'=>$request->attributes->get('fleet.user'),'guard'=>$request->attributes->get('fleet.guard')]);}
 public function requestA4(Request $request,FuelRequest $fuelRequest): View {$fuelRequest->load(['vehicle','fuelType','requester','driver','approver','creator','fueling.vehicle','fueling.driver','fueling.fuelType']);return view('reports.request-a4-two-copy',['fuelRequest'=>$fuelRequest,'fueling'=>$fuelRequest->fueling,'user'=>$request->attributes->get('fleet.user'),'guard'=>$request->attributes->get('fleet.guard')]);}
 public function authorizationThreeCopy(Request $request,FuelRequest $fuelRequest): View {if(!$fuelRequest->requiresAuthorization())abort(404,'Autorização disponível somente para requisições de 01/01/2025 em diante.');$fuelRequest->load(['vehicle','fuelType','requester','driver','approver','creator']);return view('reports.request-authorization-three-copy',['fuelRequest'=>$fuelRequest,'user'=>$request->attributes->get('fleet.user'),'guard'=>$request->attributes->get('fleet.guard')]);}
 public function authorizationThreeCopyCupom(Request $request,FuelRequest $fuelRequest): View {if(!$fuelRequest->requiresAuthorization())abort(404,'Autorização disponível somente para requisições de 01/01/2025 em diante.');$fuelRequest->load(['vehicle','fuelType','requester','driver','approver','creator']);return view('reports.request-authorization-three-copy-cupom',['fuelRequest'=>$fuelRequest,'user'=>$request->attributes->get('fleet.user'),'guard'=>$request->attributes->get('fleet.guard')]);}
 private function responsibleOptions() { $sectors=FuelRequest::query()->whereNotNull('responsible_sector')->where('responsible_sector','<>','')->distinct()->pluck('responsible_sector');$councilMembers=Person::query()->where('role','council_member')->where('active',true)->distinct()->pluck('full_name');return $sectors->merge($councilMembers)->filter()->unique()->sort()->values();}
 private function filteredQuery(Request $request): array {$filters=$request->validate(['vehicle_id'=>['nullable','integer','exists:vehicles,id'],'vehicle_status'=>['nullable','string'],'driver_person_id'=>['nullable','integer','exists:people,id'],'responsible'=>['nullable','string','max:180'],'start_date'=>['nullable','date'],'end_date'=>['nullable','date']]);$filters['vehicle_status']=$filters['vehicle_status']??'active';if(!in_array($filters['vehicle_status'],['active','maintenance','inactive','all'],true))$filters['vehicle_status']='active';$query=Fueling::query()->with(['fuelRequest.driver','vehicle','driver','fuelType'])->where('legacy_date_unreliable',false)->latest('fueling_at')->latest('id');if($filters['vehicle_status']!=='all')$query->whereHas('vehicle',fn(Builder $vehicleQuery)=>$vehicleQuery->where('status',$filters['vehicle_status']));if(!empty($filters['vehicle_id']))$query->where('vehicle_id',$filters['vehicle_id']);if(!empty($filters['driver_person_id']))$query->where(function(Builder $query)use($filters):void{$query->where('driver_person_id',$filters['driver_person_id'])->orWhereHas('fuelRequest',fn(Builder $requestQuery)=>$requestQuery->where('driver_person_id',$filters['driver_person_id']));});if(!empty($filters['responsible']))$query->whereHas('fuelRequest',function(Builder $requestQuery)use($filters):void{$requestQuery->where('responsible_sector',$filters['responsible'])->orWhereHas('requester',fn(Builder $personQuery)=>$personQuery->where('full_name',$filters['responsible']));});if(!empty($filters['start_date']))$query->where('fueling_at','>=',Carbon::parse($filters['start_date'])->startOfDay());if(!empty($filters['end_date']))$query->where('fueling_at','<=',Carbon::parse($filters['end_date'])->endOfDay());return[$filters,$query];}
}
