@extends('layouts.app',['title'=>'Indicadores · Frota Câmara'])
@section('content')
<p class="page-kicker">Gestão operacional</p><h1>Indicadores da frota</h1><p class="lede">Resumo dos registros confiáveis por período e por responsável. Veículos compartilhados não duplicam os totais gerais.</p>
<section class="surface"><form method="get" style="display:flex;align-items:end;gap:14px;flex-wrap:wrap"><label style="display:grid;gap:6px"><strong>Período</strong><select name="period" onchange="this.form.submit()"><option value="month" @selected($period['preset']==='month')>Mês e ano</option><option value="semester" @selected($period['preset']==='semester')>Último semestre</option><option value="year" @selected($period['preset']==='year')>Último ano</option></select></label><label id="month-filter" style="display:grid;gap:6px;{{ $period['preset']==='month'?'':'display:none' }}"><strong>Mês / ano</strong><input type="month" name="month" value="{{ $period['month'] ?? now()->format('Y-m') }}"></label><button style="padding:11px 16px;background:#1f6a60;border:0;border-radius:7px;color:#fff;font-weight:700">Aplicar período</button></form><p class="notice"><strong>Período selecionado:</strong> {{ $period['label'] }} · {{ $period['start']->format('d/m/Y') }} a {{ $period['end']->format('d/m/Y') }}.</p>
<div class="grid" style="margin-top:22px"><article class="card"><span class="module-icon">L</span><h2>{{ number_format($summary['fueling_liters'],3,',','.') }} L</h2><p>Volume abastecido no período</p></article><article class="card"><span class="module-icon">R$</span><h2>R$ {{ number_format($summary['fueling_amount'],2,',','.') }}</h2><p>Custo de abastecimentos no período</p></article><article class="card"><span class="module-icon">VT</span><h2>{{ $summary['active_vehicles'] }}</h2><p>Veículos ativos</p></article><article class="card"><span class="module-icon">MN</span><h2>{{ $summary['maintenance_due'] }}</h2><p>Manutenções pendentes</p></article></div>
<h2 style="margin-top:28px">Disponibilidade da frota</h2><p><strong>{{ $summary['active_vehicles'] }}</strong> veículos ativos · <strong>{{ $summary['maintenance_vehicles'] }}</strong> em manutenção · <strong>{{ $summary['inactive_vehicles'] }}</strong> inativos preservados no histórico.</p><div class="notice"><strong>Evolução de custos no período.</strong>@if(count($evolution))<div style="margin-top:10px">@foreach($evolution as $point)<span style="display:inline-block;margin:3px 12px 3px 0">{{ \Carbon\Carbon::parse($point['date'])->format('d/m') }}: R$ {{ number_format($point['amount'],2,',','.') }}</span>@endforeach</div>@else<div style="margin-top:8px">Sem abastecimentos com data confiável no intervalo.</div>@endif</div>
<h2 style="margin-top:28px">Consumo por responsável</h2><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Responsável</th><th>Litros</th><th>Total</th></tr></thead><tbody>@forelse($responsibles as $item)<tr><td>{{ $item['responsible'] }}</td><td>{{ number_format($item['liters'],3,',','.') }} L</td><td>R$ {{ number_format($item['amount'],2,',','.') }}</td></tr>@empty<tr><td colspan="3" style="padding:22px;text-align:center">Nenhum abastecimento no período.</td></tr>@endforelse</tbody></table></div></section>
<script>document.querySelector('select[name="period"]')?.addEventListener('change',function(){document.getElementById('month-filter').style.display=this.value==='month'?'grid':'none'})</script>
@endsection
